{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "56bcbabc-458e-4752-9937-d3c797b6ebdf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "\n",
    "st.set_page_config(page_title=\"Victoria Gallardo\", layout=\"wide\")\n",
    "\n",
    "df = pd.read_csv(\"airbnb.csv\")\n",
    "df.columns = [c.strip().replace(\";;\", \"\") for c in df.columns]\n",
    "\n",
    "st.title(\"Victoria Gallardo\")\n",
    "\n",
    "st.sidebar.header(\"Filters\")\n",
    "\n",
    "selected_group = st.sidebar.multiselect(\n",
    "    \"Choose neighbourhood group\",\n",
    "    sorted(df[\"neighbourhood_group\"].dropna().unique()),\n",
    "    default=sorted(df[\"neighbourhood_group\"].dropna().unique())\n",
    ")\n",
    "\n",
    "df_filtered = df[df[\"neighbourhood_group\"].isin(selected_group)]\n",
    "\n",
    "selected_room = st.sidebar.multiselect(\n",
    "    \"Choose room type\",\n",
    "    sorted(df_filtered[\"room_type\"].dropna().unique()),\n",
    "    default=sorted(df_filtered[\"room_type\"].dropna().unique())\n",
    ")\n",
    "\n",
    "df_filtered = df_filtered[df_filtered[\"room_type\"].isin(selected_room)]\n",
    "\n",
    "min_price = int(df_filtered[\"price\"].min())\n",
    "max_price = int(df_filtered[\"price\"].max())\n",
    "\n",
    "selected_price = st.sidebar.slider(\n",
    "    \"Choose price range\",\n",
    "    min_price,\n",
    "    max_price,\n",
    "    (min_price, max_price)\n",
    ")\n",
    "\n",
    "df_filtered = df_filtered[\n",
    "    (df_filtered[\"price\"] >= selected_price[0]) &\n",
    "    (df_filtered[\"price\"] <= selected_price[1])\n",
    "]\n",
    "\n",
    "col1, col2, col3 = st.columns(3)\n",
    "\n",
    "with col1:\n",
    "    st.metric(\"Listings\", len(df_filtered))\n",
    "\n",
    "with col2:\n",
    "    st.metric(\"Average price\", round(df_filtered[\"price\"].mean(), 2))\n",
    "\n",
    "with col3:\n",
    "    st.metric(\"Average reviews/month\", round(df_filtered[\"reviews_per_month\"].mean(), 2))\n",
    "\n",
    "tab1, tab2 = st.tabs([\"Dashboard\", \"Extra analysis\"])\n",
    "\n",
    "with tab1:\n",
    "    st.subheader(\"Relationship between listing type and number of people\")\n",
    "\n",
    "    fig1 = px.bar(\n",
    "        df_filtered.groupby(\"room_type\", as_index=False)[\"minimum_nights\"].mean(),\n",
    "        x=\"room_type\",\n",
    "        y=\"minimum_nights\",\n",
    "        color=\"room_type\"\n",
    "    )\n",
    "    st.plotly_chart(fig1)\n",
    "\n",
    "    col4, col5 = st.columns(2)\n",
    "\n",
    "    with col4:\n",
    "        st.subheader(\"Price by listing type\")\n",
    "        fig2 = px.bar(\n",
    "            df_filtered.groupby(\"room_type\", as_index=False)[\"price\"].mean(),\n",
    "            x=\"room_type\",\n",
    "            y=\"price\",\n",
    "            color=\"room_type\"\n",
    "        )\n",
    "        st.plotly_chart(fig2)\n",
    "\n",
    "    with col5:\n",
    "        st.subheader(\"Reviews and price\")\n",
    "        fig3 = px.scatter(\n",
    "            df_filtered,\n",
    "            x=\"number_of_reviews\",\n",
    "            y=\"price\",\n",
    "            color=\"room_type\"\n",
    "        )\n",
    "        st.plotly_chart(fig3)\n",
    "\n",
    "with tab2:\n",
    "    st.subheader(\"Top apartments by reviews per month\")\n",
    "\n",
    "    top_apartments = df_filtered.sort_values(\n",
    "        \"reviews_per_month\",\n",
    "        ascending=False\n",
    "    ).head(10)\n",
    "\n",
    "    fig4 = px.bar(\n",
    "        top_apartments,\n",
    "        x=\"name\",\n",
    "        y=\"reviews_per_month\",\n",
    "        color=\"neighbourhood_group\"\n",
    "    )\n",
    "    st.plotly_chart(fig4)\n",
    "\n",
    "    st.subheader(\"Data table\")\n",
    "    st.dataframe(df_filtered)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9fdf4f91-0d55-48a6-8dcf-652c588b830d",
   "metadata": {},
   "outputs": [],
   "source": [
    "!streamlit run app.py"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7bd461b0-04af-4f22-b1d2-ad9e9f5ecc7a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
